-- BVME ChadRank production voting schema
create table if not exists public.votes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  member_id bigint not null,
  category text not null check (category in ('Presentation','Creativity','Photo Quality','Community')),
  created_at timestamptz not null default now(),
  unique(user_id, category)
);

alter table public.votes enable row level security;

revoke all on public.votes from anon;
grant select, insert on public.votes to authenticated;

drop policy if exists "users can see their own votes" on public.votes;
create policy "users can see their own votes"
on public.votes for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "users can insert their own votes" on public.votes;
create policy "users can insert their own votes"
on public.votes for insert to authenticated
with check ((select auth.uid()) = user_id);

create or replace function public.cast_vote(p_member_id bigint, p_category text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'You must be signed in'; end if;
  if p_category not in ('Presentation','Creativity','Photo Quality','Community') then raise exception 'Invalid category'; end if;
  insert into public.votes(user_id, member_id, category)
  values(auth.uid(), p_member_id, p_category);
end;
$$;

revoke all on function public.cast_vote(bigint,text) from public;
grant execute on function public.cast_vote(bigint,text) to authenticated;

create or replace function public.get_vote_counts()
returns table(member_id bigint, category text, votes bigint)
language sql
security definer
set search_path = public
as $$
  select v.member_id, v.category, count(*)::bigint
  from public.votes v
  group by v.member_id, v.category;
$$;

revoke all on function public.get_vote_counts() from public;
grant execute on function public.get_vote_counts() to anon, authenticated;
